import image4 from "../assets/image4.png";
//  import image5 from "../assets/image5.jpeg";
// //  import webpage from "../assets/webpage.png";
// import image6 from "../assets/image6.jpg";
import image7 from "../assets/image7.png";


const ProjectCardData =[
    {
        imgsrc: image4,
        title:"Sculpture Management System",
        text : "In this project, developed a system as a search engine for finding the temple sculpture details. Using this system we can search for an image of a sculpture, the system will provide the entire sculpture details like the name of the sculpture, temple name, state, and city of the temple.",
        view :"https://docs.google.com/presentation/d/16lla9I3rb5vdtE9Z71PKyOlOimRNSgpI/edit?usp=sharing&ouid=111649854948101651140&rtpof=true&sd=true",
        source:"https://github.com/surya0811/temple-sculpture.git",
    },
    // {
    //     imgsrc: image5,
    //     title:"Real Time Object Detection",
    //     text : "In this project, developed a system .it helps in finding the name of the particular object which is near to the web camera so that identification cna be done here",
    //     view :"file:///E:/Assetmanagement-main/reports/REPORT.pdf",
    //     source:"https://github.com/surya0811/Assetmanagement1.git",
    // },
    // {
    //     imgsrc: image6,
    //     title:"Email Sender Using Node Mailer",
    //     text : "In this project, developed a system .it helps in sending  the email using snmp protocol which is generated by the 16 bit passcode ",
    //     view :"",
    //     source:"https://github.com/surya0811/emailsender.git",
    // },
    {
        imgsrc: image7,
        title:"Asset management system",
        text : "In this project, we developed a system for effective management of asset for organizations to optimize their resources and streamline operations. This abstract introduces an innovative Asset Management System built on the MERN (MySQL, Express, React, Node) stack, designed to efficiently manage product data ",
        view :"",
        source:"https://github.com/surya0811/Assetmanagement1.git",
    }

];

export default ProjectCardData;