import image4 from "../assets/image4.png";
 import image5 from "../assets/image5.jpeg";
//  import webpage from "../assets/webpage.png";


const ProjectCardData =[
    {
        imgsrc: image4,
        title:"Sculpture Management System",
        text : "In this project, developed a system as a search engine for finding the temple sculpture details. Using this system we can search for an image of a sculpture, the system will provide the entire sculpture details like the name of the sculpture, temple name, state, and city of the temple.",
        view :"https://docs.google.com/presentation/d/16lla9I3rb5vdtE9Z71PKyOlOimRNSgpI/edit?usp=sharing&ouid=111649854948101651140&rtpof=true&sd=true",
        source:"https://github.com/surya0811/temple-sculpture.git",
    },
    {
        imgsrc: image5,
        title:"Real Time Object Detection",
        text : "In this project, developed a system .it helps in finding the name of the particular object which is near to the web camera so that identification cna be done here",
        view :"https://www.irjet.net/archives/V7/i4/IRJET-V7I4621.pdf",
        source:"https://github.com/surya0811/real-time-object-detection.git",
    },
    {
        imgsrc: image4,
        title:"Email Sender Using Node Mailer",
        text : "In this project, developed a system .it helps in sending  the email using snmp protocol which is generated by the 16 bit passcode ",
        view :"https://www.irjet.net/archives/V7/i4/IRJET-V7I4621.pdf",
        source:"",
    }
];

export default ProjectCardData;